# List of humanitarian sites that are taken as candidate.
sites:
  #- global
  #- armenia
  #- bangladesh
  #- cambodia
  #- china
  #- eca
  - india
  #- peru
  #- ukraine
  #- vietnam

# Low level and high level langauges.
allowed_languages:
  - ar
  - es
  - fr
  - zh
  - en
  - hy
  - bn
  - km
  - zh-hans
  - bg
  - cs
  - hr
  - hu
  - pl
  - ru
  - sk
  - sq
  - sr
  - uk
  - as
  - ben
  - gu
  - hi
  - kn
  - ml
  - mr
  - or
  - tam
  - te
  - ur
  - qu
  - shp
